/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/_dashboard'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/userId'
import { Route as AuthenticatedDashboardMeetingsIndexRouteImport } from './routes/_authenticated/_dashboard/meetings/index'
import { Route as AuthenticatedDashboardAgentsIndexRouteImport } from './routes/_authenticated/_dashboard/agents/index'
import { Route as AuthenticatedDashboardMeetingsMeetingIdRouteImport } from './routes/_authenticated/_dashboard/meetings/$meetingId'
import { Route as AuthenticatedDashboardAgentsAgentIdRouteImport } from './routes/_authenticated/_dashboard/agents/$agentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/userId',
    path: '/users/userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardMeetingsIndexRoute =
  AuthenticatedDashboardMeetingsIndexRouteImport.update({
    id: '/meetings/',
    path: '/meetings/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAgentsIndexRoute =
  AuthenticatedDashboardAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMeetingsMeetingIdRoute =
  AuthenticatedDashboardMeetingsMeetingIdRouteImport.update({
    id: '/meetings/$meetingId',
    path: '/meetings/$meetingId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAgentsAgentIdRoute =
  AuthenticatedDashboardAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/users/userId': typeof AuthenticatedUsersUserIdRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/agents/$agentId': typeof AuthenticatedDashboardAgentsAgentIdRoute
  '/meetings/$meetingId': typeof AuthenticatedDashboardMeetingsMeetingIdRoute
  '/agents': typeof AuthenticatedDashboardAgentsIndexRoute
  '/meetings': typeof AuthenticatedDashboardMeetingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/users/userId': typeof AuthenticatedUsersUserIdRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/agents/$agentId': typeof AuthenticatedDashboardAgentsAgentIdRoute
  '/meetings/$meetingId': typeof AuthenticatedDashboardMeetingsMeetingIdRoute
  '/agents': typeof AuthenticatedDashboardAgentsIndexRoute
  '/meetings': typeof AuthenticatedDashboardMeetingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/users/userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/_dashboard/agents/$agentId': typeof AuthenticatedDashboardAgentsAgentIdRoute
  '/_authenticated/_dashboard/meetings/$meetingId': typeof AuthenticatedDashboardMeetingsMeetingIdRoute
  '/_authenticated/_dashboard/agents/': typeof AuthenticatedDashboardAgentsIndexRoute
  '/_authenticated/_dashboard/meetings/': typeof AuthenticatedDashboardMeetingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/users/userId'
    | '/users'
    | '/agents/$agentId'
    | '/meetings/$meetingId'
    | '/agents'
    | '/meetings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/users/userId'
    | '/users'
    | '/agents/$agentId'
    | '/meetings/$meetingId'
    | '/agents'
    | '/meetings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/_dashboard'
    | '/_authenticated/users/userId'
    | '/_authenticated/users/'
    | '/_authenticated/_dashboard/agents/$agentId'
    | '/_authenticated/_dashboard/meetings/$meetingId'
    | '/_authenticated/_dashboard/agents/'
    | '/_authenticated/_dashboard/meetings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/userId': {
      id: '/_authenticated/users/userId'
      path: '/users/userId'
      fullPath: '/users/userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/meetings/': {
      id: '/_authenticated/_dashboard/meetings/'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedDashboardMeetingsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/agents/': {
      id: '/_authenticated/_dashboard/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedDashboardAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/meetings/$meetingId': {
      id: '/_authenticated/_dashboard/meetings/$meetingId'
      path: '/meetings/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof AuthenticatedDashboardMeetingsMeetingIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/agents/$agentId': {
      id: '/_authenticated/_dashboard/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedDashboardAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAgentsAgentIdRoute: typeof AuthenticatedDashboardAgentsAgentIdRoute
  AuthenticatedDashboardMeetingsMeetingIdRoute: typeof AuthenticatedDashboardMeetingsMeetingIdRoute
  AuthenticatedDashboardAgentsIndexRoute: typeof AuthenticatedDashboardAgentsIndexRoute
  AuthenticatedDashboardMeetingsIndexRoute: typeof AuthenticatedDashboardMeetingsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAgentsAgentIdRoute:
      AuthenticatedDashboardAgentsAgentIdRoute,
    AuthenticatedDashboardMeetingsMeetingIdRoute:
      AuthenticatedDashboardMeetingsMeetingIdRoute,
    AuthenticatedDashboardAgentsIndexRoute:
      AuthenticatedDashboardAgentsIndexRoute,
    AuthenticatedDashboardMeetingsIndexRoute:
      AuthenticatedDashboardMeetingsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
