// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agent (name, user_id, instructions)
VALUES ($1, $2, $3)
RETURNING id, name, user_id, instructions, created_at, updated_at
`

type CreateAgentParams struct {
	Name         string `db:"name" json:"name"`
	UserID       string `db:"user_id" json:"userId"`
	Instructions string `db:"instructions" json:"instructions"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent, arg.Name, arg.UserID, arg.Instructions)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agent WHERE id = $1 AND user_id = $2
`

type DeleteAgentParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID string    `db:"user_id" json:"userId"`
}

func (q *Queries) DeleteAgent(ctx context.Context, arg DeleteAgentParams) error {
	_, err := q.db.Exec(ctx, deleteAgent, arg.ID, arg.UserID)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT
 a.id, a.name, a.user_id, a.instructions, a.created_at, a.updated_at,
 COALESCE(m.meeting_count, 0) AS meeting_count
FROM agent a
LEFT JOIN (
    SELECT agent_id, COUNT(*) AS meeting_count
    FROM meeting
    WHERE agent_id = $1
    GROUP BY agent_id
) m ON a.id = m.agent_id
WHERE a.id = $1 AND a.user_id = $2
`

type GetAgentParams struct {
	AgentID uuid.UUID `db:"agent_id" json:"agentId"`
	UserID  string    `db:"user_id" json:"userId"`
}

type GetAgentRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	UserID       string    `db:"user_id" json:"userId"`
	Instructions string    `db:"instructions" json:"instructions"`
	CreatedAt    time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt    time.Time `db:"updated_at" json:"updatedAt"`
	MeetingCount int64     `db:"meeting_count" json:"meetingCount"`
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.AgentID, arg.UserID)
	var i GetAgentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MeetingCount,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, name, user_id, instructions, created_at, updated_at FROM agent WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgents = `-- name: GetAgents :many
SELECT
    a.id,
    a.name,
    a.instructions,
    a.user_id,
    a.created_at,
    a.updated_at,
    COUNT(m.id) AS meeting_count,
    COUNT(*) OVER() AS total_count
FROM agent a
LEFT JOIN meeting m ON a.id = m.agent_id
WHERE a.user_id = $1
  AND ($2::text = '' OR a.name ILIKE '%' || $2 || '%')
GROUP BY
    a.id,
    a.name,
    a.instructions,
    a.user_id,
    a.created_at,
    a.updated_at
ORDER BY a.updated_at DESC
LIMIT $3 OFFSET $4
`

type GetAgentsParams struct {
	UserID  string `db:"user_id" json:"userId"`
	Column2 string `db:"column_2" json:"column2"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type GetAgentsRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Instructions string    `db:"instructions" json:"instructions"`
	UserID       string    `db:"user_id" json:"userId"`
	CreatedAt    time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt    time.Time `db:"updated_at" json:"updatedAt"`
	MeetingCount int64     `db:"meeting_count" json:"meetingCount"`
	TotalCount   int64     `db:"total_count" json:"totalCount"`
}

func (q *Queries) GetAgents(ctx context.Context, arg GetAgentsParams) ([]GetAgentsRow, error) {
	rows, err := q.db.Query(ctx, getAgents,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAgentsRow{}
	for rows.Next() {
		var i GetAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Instructions,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MeetingCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agent
SET name = $2, instructions = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, user_id, instructions, created_at, updated_at
`

type UpdateAgentParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Instructions string    `db:"instructions" json:"instructions"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent, arg.ID, arg.Name, arg.Instructions)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
