// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agent (name, user_id, instructions)
VALUES ($1, $2, $3)
RETURNING id, name, user_id, instructions, created_at, updated_at
`

type CreateAgentParams struct {
	Name         string `db:"name" json:"name"`
	UserID       string `db:"user_id" json:"userId"`
	Instructions string `db:"instructions" json:"instructions"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent, arg.Name, arg.UserID, arg.Instructions)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agent WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const deleteAgentsByUserID = `-- name: DeleteAgentsByUserID :exec
DELETE FROM agent WHERE user_id = $1
`

func (q *Queries) DeleteAgentsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAgentsByUserID, userID)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, user_id, instructions, created_at, updated_at FROM agent WHERE id = $1 AND user_id = $2
`

type GetAgentParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID string    `db:"user_id" json:"userId"`
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.ID, arg.UserID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, name, user_id, instructions, created_at, updated_at FROM agent WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgents = `-- name: GetAgents :many
SELECT id, name, user_id, instructions, created_at, updated_at FROM agent WHERE user_id = $1
`

func (q *Queries) GetAgents(ctx context.Context, userID string) ([]Agent, error) {
	rows, err := q.db.Query(ctx, getAgents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Instructions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agent
SET name = $2, instructions = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, user_id, instructions, created_at, updated_at
`

type UpdateAgentParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Instructions string    `db:"instructions" json:"instructions"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent, arg.ID, arg.Name, arg.Instructions)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
