// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chat.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO meeting_chat_messages (
    meeting_id,
    user_id,
    role,
    content
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, meeting_id, user_id, role, content, created_at
`

type CreateChatMessageParams struct {
	MeetingID uuid.UUID `db:"meeting_id" json:"meetingId"`
	UserID    string    `db:"user_id" json:"userId"`
	Role      string    `db:"role" json:"role"`
	Content   string    `db:"content" json:"content"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (MeetingChatMessages, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.MeetingID,
		arg.UserID,
		arg.Role,
		arg.Content,
	)
	var i MeetingChatMessages
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT id, meeting_id, user_id, role, content, created_at FROM meeting_chat_messages
WHERE meeting_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetChatMessages(ctx context.Context, meetingID uuid.UUID) ([]MeetingChatMessages, error) {
	rows, err := q.db.Query(ctx, getChatMessages, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingChatMessages{}
	for rows.Next() {
		var i MeetingChatMessages
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentChatMessages = `-- name: GetRecentChatMessages :many
SELECT id, meeting_id, user_id, role, content, created_at FROM meeting_chat_messages
WHERE meeting_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentChatMessagesParams struct {
	MeetingID uuid.UUID `db:"meeting_id" json:"meetingId"`
	Limit     int32     `db:"limit" json:"limit"`
}

func (q *Queries) GetRecentChatMessages(ctx context.Context, arg GetRecentChatMessagesParams) ([]MeetingChatMessages, error) {
	rows, err := q.db.Query(ctx, getRecentChatMessages, arg.MeetingID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingChatMessages{}
	for rows.Next() {
		var i MeetingChatMessages
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
