// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: meetings.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMeeting = `-- name: CreateMeeting :one
INSERT INTO meeting (name, user_id, agent_id)
VALUES ($1, $2, $3)
RETURNING id, name, user_id, agent_id, start_time, end_time, status, transcript_url, recording_url, summary, created_at, updated_at
`

type CreateMeetingParams struct {
	Name    string    `db:"name" json:"name"`
	UserID  string    `db:"user_id" json:"userId"`
	AgentID uuid.UUID `db:"agent_id" json:"agentId"`
}

func (q *Queries) CreateMeeting(ctx context.Context, arg CreateMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, createMeeting, arg.Name, arg.UserID, arg.AgentID)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.AgentID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.TranscriptUrl,
		&i.RecordingUrl,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMeeting = `-- name: DeleteMeeting :exec
DELETE FROM meeting WHERE id = $1
`

func (q *Queries) DeleteMeeting(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeeting, id)
	return err
}

const deleteMeetingsByUserID = `-- name: DeleteMeetingsByUserID :exec
DELETE FROM meeting WHERE user_id = $1
`

func (q *Queries) DeleteMeetingsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteMeetingsByUserID, userID)
	return err
}

const getMeeting = `-- name: GetMeeting :one
SELECT
    m.id,
    m.name,
    m.user_id,
    m.agent_id,
    m.start_time,
    m.end_time,
    m.status,
    m.created_at,
    m.updated_at,
    a.name AS agent_name,
    a.instructions AS agent_instructions
FROM meeting AS m
JOIN agent AS a
    ON m.agent_id = a.id
WHERE m.id = $1
    AND m.user_id = $2
`

type GetMeetingParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID string    `db:"user_id" json:"userId"`
}

type GetMeetingRow struct {
	ID                uuid.UUID  `db:"id" json:"id"`
	Name              string     `db:"name" json:"name"`
	UserID            string     `db:"user_id" json:"userId"`
	AgentID           uuid.UUID  `db:"agent_id" json:"agentId"`
	StartTime         *time.Time `db:"start_time" json:"startTime"`
	EndTime           *time.Time `db:"end_time" json:"endTime"`
	Status            string     `db:"status" json:"status"`
	CreatedAt         time.Time  `db:"created_at" json:"createdAt"`
	UpdatedAt         time.Time  `db:"updated_at" json:"updatedAt"`
	AgentName         string     `db:"agent_name" json:"agentName"`
	AgentInstructions string     `db:"agent_instructions" json:"agentInstructions"`
}

func (q *Queries) GetMeeting(ctx context.Context, arg GetMeetingParams) (GetMeetingRow, error) {
	row := q.db.QueryRow(ctx, getMeeting, arg.ID, arg.UserID)
	var i GetMeetingRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.AgentID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentName,
		&i.AgentInstructions,
	)
	return i, err
}

const getMeetingByID = `-- name: GetMeetingByID :one
SELECT id, name, user_id, agent_id, start_time, end_time, status, transcript_url, recording_url, summary, created_at, updated_at FROM meeting WHERE id = $1
`

func (q *Queries) GetMeetingByID(ctx context.Context, id uuid.UUID) (Meeting, error) {
	row := q.db.QueryRow(ctx, getMeetingByID, id)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.AgentID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.TranscriptUrl,
		&i.RecordingUrl,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeetings = `-- name: GetMeetings :many
SELECT
    m.id,
    m.name,
    m.user_id,
    m.agent_id,
    m.start_time,
    m.end_time,
    m.status,
    m.created_at,
    m.updated_at,
    COUNT(*) OVER() as total_count,
    a.name AS agent_name,
    a.instructions AS agent_instructions
FROM meeting AS m
JOIN agent AS a
    ON m.agent_id = a.id
WHERE m.user_id = $1
    AND (
        CASE
            WHEN $2::text != '' THEN m.name ILIKE '%' || $2 || '%'
            ELSE TRUE
        END
    )
ORDER BY m.updated_at DESC
LIMIT $3 OFFSET $4
`

type GetMeetingsParams struct {
	UserID  string `db:"user_id" json:"userId"`
	Column2 string `db:"column_2" json:"column2"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type GetMeetingsRow struct {
	ID                uuid.UUID  `db:"id" json:"id"`
	Name              string     `db:"name" json:"name"`
	UserID            string     `db:"user_id" json:"userId"`
	AgentID           uuid.UUID  `db:"agent_id" json:"agentId"`
	StartTime         *time.Time `db:"start_time" json:"startTime"`
	EndTime           *time.Time `db:"end_time" json:"endTime"`
	Status            string     `db:"status" json:"status"`
	CreatedAt         time.Time  `db:"created_at" json:"createdAt"`
	UpdatedAt         time.Time  `db:"updated_at" json:"updatedAt"`
	TotalCount        int64      `db:"total_count" json:"totalCount"`
	AgentName         string     `db:"agent_name" json:"agentName"`
	AgentInstructions string     `db:"agent_instructions" json:"agentInstructions"`
}

func (q *Queries) GetMeetings(ctx context.Context, arg GetMeetingsParams) ([]GetMeetingsRow, error) {
	rows, err := q.db.Query(ctx, getMeetings,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMeetingsRow{}
	for rows.Next() {
		var i GetMeetingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.AgentID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
			&i.AgentName,
			&i.AgentInstructions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeeting = `-- name: UpdateMeeting :one
UPDATE meeting
SET
    name = COALESCE($2, name),
    agent_id = COALESCE($3, agent_id),
    status = COALESCE($4, status),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, user_id, agent_id, start_time, end_time, status, transcript_url, recording_url, summary, created_at, updated_at
`

type UpdateMeetingParams struct {
	ID      uuid.UUID `db:"id" json:"id"`
	Name    string    `db:"name" json:"name"`
	AgentID uuid.UUID `db:"agent_id" json:"agentId"`
	Status  string    `db:"status" json:"status"`
}

func (q *Queries) UpdateMeeting(ctx context.Context, arg UpdateMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, updateMeeting,
		arg.ID,
		arg.Name,
		arg.AgentID,
		arg.Status,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.AgentID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.TranscriptUrl,
		&i.RecordingUrl,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
